import { FormData } from "./types"

export function buildPrdPrompt(data: FormData): string {
  const sections = [
    "=== PROJECT INFORMATION ===",
    "",
    "Project Name: " + data.project_name,
    "Description: " + data.idea_description,
    "Target Users: " + data.target_user,
    "Platform: " + data.platform,
    "Timeline: " + data.timeline,
    "Features: " + data.features,
    "Tech Stack: " + data.tech_stack,
    "References: " + data.reference_links,
    "",
    "=== OUTPUT REQUIREMENTS ===",
    "",
    "Generate a Product Requirement Document with the EXACT 8-component structure below. EVERY section MUST be bilingual (English first, then Indonesian paragraph).",
    "",
    "---",
    "",
    "## 1. Judul & Metadata",
    "Project name, version, date, and author information (EN + ID)",
    "",
    "## 2. Ringkasan Eksekutif / Executive Summary",
    "Brief product overview and why it exists (2 paragraphs EN, 2 paragraphs ID)",
    "",
    "## 3. Tujuan & Metrik / Goals & Metrics",
    "Product vision and measurable success metrics (EN + ID)",
    "",
    "## 4. Pernyataan Masalah / Problem Statement",
    "User problem or pain point this product solves (EN + ID)",
    "",
    "## 5. Target Pengguna / Target Users",
    "User personas, demographics, and user needs (EN + ID)",
    "",
    "## 6. Ruang Lingkup Fitur / Feature Scope",
    "Core features list with priority (MVP vs future), specifications (EN + ID)",
    "",
    "## 7. User Flow & Desain / User Flow & Design",
    "",
    "Include a MERMAID flowchart diagram code block. Use this EXACT format:",
    "",
    "```mermaid",
    "flowchart TD",
    "  A[Landing Page] --> B[Sign Up]",
    "  B --> C[Dashboard]",
    "  C --> D[Feature X]",
    "  C --> E[Feature Y]",
    "  D --> F[Logout]",
    "  E --> F",
    "```",
    "",
    "MERMAID RULES (strictly follow these):",
    "- Start with exactly: flowchart TD",
    "- Each node: one LETTER as ID, then SHAPE: [text] for rectangle, {text} for diamond, (text) for rounded",
    "- Node IDs: single capital letters only (A, B, C, D, E, F...)",
    "- Arrows: simple --> with NO text labels on arrows",
    "- Node labels: use ONLY alphanumeric characters and spaces. NO quotes, NO commas, NO special chars",
    "- Each line: one node definition OR one connection, never both on same line",
    "- Keep it simple: max 8-10 nodes showing the main user journey",
    "- Example valid line: C --> D",
    "- Example valid node: D[Edit Profile]",
    "",
    "## 8. Asumsi & Pertanyaan Terbuka / Assumptions & Open Questions",
    "Known assumptions, risks, and unresolved questions (EN + ID)",
    "",
    "---",
    "",
    "After the PRD sections above, add this final section:",
    "",
    "## Vibe Coding Prompt / Prompt untuk Vibe Coding",
    "",
    "Generate a detailed step-by-step prompt that a vibe coder can copy-paste into Cursor, Claude, or ChatGPT to build this project.",
    "",
    "The vibe coding prompt must be structured as PHASES following the user flow:",
    "- Phase 1: Project setup and configuration",
    "- Phase 2: Authentication and user management",
    "- Phase 3: Core feature 1 implementation",
    "- Phase 4: Core feature 2 implementation",
    "- And so on based on the features",
    "- Phase N: Polish, testing, and deployment",
    "",
    "Each phase must include: concrete file names, component structure, data flow, route design, and code snippets.",
    "Write the vibe coding prompt in English only.",
    "",
    "IMPORTANT FORMATTING RULES:",
    "- Use ## and ### for Markdown headings",
    "- Each section must have both English and Indonesian content",
    "- The mermaid block must be valid syntax (strictly follow the rules above)",
    "- Total length: 1500-2500 words",
  ]

  return sections.join("\n")
}

export function buildVibePrompt(data: FormData, prdContent: string): string {
  const lines = [
    "You are an expert full-stack developer. Build the following project following the PRD below.",
    "Generate the implementation in STEP-BY-STEP phases.",
    "",
    "PROJECT: " + data.project_name,
    "TECH STACK: " + data.tech_stack,
    "PLATFORM: " + data.platform,
    "",
    "KEY FEATURES:",
    data.features,
    "",
    "PRD REFERENCE:",
    prdContent.substring(0, 4000),
    "",
    "=== OUTPUT STRUCTURE ===",
    "",
    "Phase 1: Project Setup",
    "- Create project structure, dependencies, environment variables",
    "- Database schema and migrations",
    "- Folder structure",
    "",
    "Phase 2: Authentication & User Management",
    "- Login, register, session handling",
    "- User profile",
    "",
    "Phase 3: Core Feature Implementation",
    "- Implement each feature one by one",
    "- Include file paths, component code, API routes",
    "",
    "Phase 4: User Flow Completion",
    "- Connect all features following the user flow",
    "- Navigation, routing, state management",
    "",
    "Phase 5: Polish & Deploy",
    "- Error handling, loading states, responsive UI",
    "- Deployment instructions",
    "",
    "For each phase provide:",
    "- Complete file paths (e.g., src/app/page.tsx)",
    "- Full code implementation",
    "- Brief explanation of what the code does",
    "",
    "Make it production-ready with proper TypeScript types and error handling.",
  ]

  return lines.join("\n")
}
